/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mahbub.codeshare;
import javax.swing.JOptionPane;

// Basic Message


/**
 *
 * @author mahbub
 */
public class MainUI extends javax.swing.JFrame {
    public static String MID = MachineHardwareIdentifier.getUniqueId();
    static String joinUID = MachineHardwareIdentifier.getUniqueId();
    private static String userCode;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /** Creates new form MainUI */

    
    public MainUI() {
        initComponents();
        FirebaseInitializer.initialize();
        
        MachineID.setText(MID);
        MachineID.setEditable(false);
        
        
        
        
        

    /*// Add this manual listener to track typing/deleting
    jTextArea2.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { syncWithFirebase(); }
        
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { syncWithFirebase(); }
        
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { syncWithFirebase(); }

      private void syncWithFirebase() {
    String code = jTextArea2.getText();
    
    // Start a new thread so the UI doesn't freeze
    new Thread(() -> {
        try {
            AddData.addUser(code); 
        } catch (Exception ex) {
            // Log the error without crashing the UI
            java.util.logging.Logger.getLogger(MainUI.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }).start();
}
    });
*/
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        SendCode = new javax.swing.JButton();
        ReloadCode = new javax.swing.JButton();
        CompileCBtn = new javax.swing.JButton();
        CompileCppBtn = new javax.swing.JButton();
        MachineID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomID = new javax.swing.JTextPane();
        joinButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AboutBtn = new javax.swing.JButton();
        CreateYours = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.addHierarchyListener(this::jTextArea2HierarchyChanged);
        jScrollPane2.setViewportView(jTextArea2);

        SendCode.setText("Update");
        SendCode.addActionListener(this::SendCodeActionPerformed);

        ReloadCode.setText("Reload");
        ReloadCode.addActionListener(this::ReloadCodeActionPerformed);

        CompileCBtn.setText("C");
        CompileCBtn.addActionListener(this::CompileCBtnActionPerformed);

        CompileCppBtn.setText("C++");
        CompileCppBtn.addActionListener(this::CompileCppBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ReloadCode)
                .addGap(43, 43, 43)
                .addComponent(SendCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CompileCBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompileCppBtn)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReloadCode)
                    .addComponent(SendCode)
                    .addComponent(CompileCBtn)
                    .addComponent(CompileCppBtn))
                .addGap(25, 25, 25))
        );

        MachineID.setMaximumSize(new java.awt.Dimension(500, 500));
        MachineID.setMinimumSize(new java.awt.Dimension(500, 500));

        roomID.setToolTipText("");
        jScrollPane1.setViewportView(roomID);

        joinButton.setText("Join");
        joinButton.addActionListener(this::joinButtonActionPerformed);

        jLabel1.setText("MY MACHINE UID");

        jLabel2.setText("Or enter Someone else UID here to Join");

        AboutBtn.setText("?");
        AboutBtn.addActionListener(this::AboutBtnActionPerformed);

        CreateYours.setText("Join Yours");
        CreateYours.addActionListener(this::CreateYoursActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MachineID, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(AboutBtn)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CreateYours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(joinButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MachineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(AboutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(CreateYours)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(joinButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTextArea2HierarchyChanged
        

        
        
    }//GEN-LAST:event_jTextArea2HierarchyChanged

    private void SendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendCodeActionPerformed
        try {
                GetData.getCode();
            } catch (Exception ex) {
                System.getLogger(MainUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        if (GetData.isExist && GetData.isLocked.equals("false")) {

            userCode = jTextArea2.getText();

            try {
                AddData.addUser(userCode);
            } catch (Exception ex) {
                System.getLogger(MainUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, "** Maybe You are not joined In a valid room \n**Or Code sending permission is Off. Ask room creator");
        }


    }//GEN-LAST:event_SendCodeActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed

        if (roomID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Room ID cant be empty");
        } else {
            String oldUID = joinUID;
            joinUID = roomID.getText();
            boolean isFound = false;

            try {
                
                GetData.getCode();
                isFound = GetData.isExist;

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to fetch data: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            if (!isFound) {
                JOptionPane.showMessageDialog(this, "Invalid Room:" + joinUID+"\nCreate your own or enter valid UID");
                joinUID = oldUID;
            } else {
                if (joinUID.equals(MID))
                {
                    JOptionPane.showMessageDialog(this, "Joined Your Own Room :" + joinUID);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Joined Room :" + joinUID + isFound);
                }
                
            }
        }
    }//GEN-LAST:event_joinButtonActionPerformed

    private void ReloadCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadCodeActionPerformed
     try {
       GetData.getCode();
       
        
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to fetch data: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
     
     if (GetData.isExist)
     {
         userCode = GetData.Code;
        jTextArea2.setText(userCode);
     }
     else
     {
         JOptionPane.showMessageDialog(this, "Invalid Room :" + joinUID);
     }
    }//GEN-LAST:event_ReloadCodeActionPerformed

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
        JOptionPane.showMessageDialog(this, "Server Info \n\nJoined Room :" + joinUID+"\n\nDev Info\nDeveloped by, Md Mahbub Tanmay\nDepartment of Software Engineering, UFTB");
    }//GEN-LAST:event_AboutBtnActionPerformed

    private void CompileCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompileCBtnActionPerformed
        CompileCode.CompileC(jTextArea2.getText(), this);
    }//GEN-LAST:event_CompileCBtnActionPerformed

    private void CreateYoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateYoursActionPerformed

        joinUID = MID;


        try {

            GetData.getCode();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to fetch data: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        if (!GetData.isExist) {

            try {
                AddData.createUser("//New Room created");
                jTextArea2.setText("//New Room created");
                JOptionPane.showMessageDialog(this, "Your Room created");
            } catch (Exception ex) {
                System.getLogger(MainUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Joined your own room");
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
                
                
            
         
            
            
    }//GEN-LAST:event_CreateYoursActionPerformed

    private void CompileCppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompileCppBtnActionPerformed
        CompileCode.CompileCpp(jTextArea2.getText(), this);
    }//GEN-LAST:event_CompileCppBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JButton CompileCBtn;
    private javax.swing.JButton CompileCppBtn;
    private javax.swing.JButton CreateYours;
    private javax.swing.JTextField MachineID;
    private javax.swing.JButton ReloadCode;
    private javax.swing.JButton SendCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton joinButton;
    private javax.swing.JTextPane roomID;
    // End of variables declaration//GEN-END:variables

}
